# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

priceEuropeanOption <- function(nInt, barrier, strike, spot, vol, r, expiry, nReps) {
    .Call(`_BarrierOptionPrices_priceEuropeanOption`, nInt, barrier, strike, spot, vol, r, expiry, nReps)
}

rcpp_hello_world <- function() {
    .Call(`_BarrierOptionPrices_rcpp_hello_world`)
}

